parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

when@dev:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
        App\Tests\Fixtures\:
            resource: '../tests/Fixtures/'
